# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=14, unique=True, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(default=2000, verbose_name='出生年份')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出生月份')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出生日期')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人头像')),
                ('location', models.CharField(choices=[('hz', '杭州'), ('nb', '宁波'), ('wz', '温州'), ('jx', '嘉兴')], max_length=8, verbose_name='地址')),
            ],
        ),
    ]
